'use strict';
let KEY='habitlab-v1';
let course=[],week=0,day=0,tab='learn',state={solved:[],practice:[],drafts:{},checks:{},codeSnapshots:{},last:0,name:''},storageOK=true;
const weeks=[{title:'Kotlin + Android',label:'Приложение',color:'#a391ff',goal:'Compose, Views, корутины и сетевой клиент'},{title:'Java + админка',label:'Управление',color:'#ffbf7e',goal:'Модели, сервисы, тесты и шаблоны'},{title:'Spring Boot',label:'Общий бэкенд',color:'#78e2b8',goal:'REST API, JPA, безопасность и интеграция'}];
const $=s=>document.querySelector(s);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function cleanProgressMap(value,kind){const result={};if(!value||typeof value!=='object'||Array.isArray(value))return result;for(const [key,item] of Object.entries(value)){if(!/^(?:[0-9]|1[0-9]|20)$/.test(key))continue;if(kind==='checks'&&Array.isArray(item))result[key]=[...new Set(item.filter(x=>Number.isInteger(x)&&x>=0&&x<20))];else if(kind!=='checks'&&typeof item==='string')result[key]=item;}return result;}
function validateState(v){if(!v||typeof v!=='object'||!Array.isArray(v.solved)||!Array.isArray(v.practice))throw Error('Неверный формат прогресса');return {solved:[...new Set(v.solved.filter(x=>typeof x==='string'&&/^\d+-(code|quiz)$/.test(x)&&Number(x.split('-')[0])<21))],practice:[...new Set(v.practice.filter(x=>Number.isInteger(x)&&x>=0&&x<21))],drafts:cleanProgressMap(v.drafts,'drafts'),checks:cleanProgressMap(v.checks,'checks'),codeSnapshots:cleanProgressMap(v.codeSnapshots,'codeSnapshots'),last:Number.isInteger(v.last)&&v.last>=0&&v.last<21?v.last:0,name:typeof v.name==='string'?v.name.slice(0,80):''};}
try{const raw=localStorage.getItem(KEY);if(raw)state=validateState(JSON.parse(raw));}catch(e){storageOK=false;}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){storageOK=false;}$('#storageMessage').textContent=storageOK?'':'Сохранение недоступно. Экспортируй прогресс перед закрытием.';updateProfile();window.onProgressSaved?.();}
function completed(i){return state.solved.includes(i+'-code')&&state.solved.includes(i+'-quiz')&&state.practice.includes(i);}
function score(){return state.solved.length*50+state.practice.length*100;}
function updateProfile(){const count=Array.from({length:21},(_,i)=>i).filter(completed).length;const xp=score();$('#level').textContent=xp<600?'Исследователь':xp<1600?'Разработчик':xp<3000?'Инженер':'Архитектор';$('#xp').textContent=`${xp} / 4200 XP · ${count} / 21 дней`;$('#totalBar').style.width=(xp/4200*100)+'%';$('#certificate').textContent=count===21?'Получить сертификат':'Сертификат · '+count+'/21';}
function selectDay(index){if(!Number.isInteger(index)||index<0||index>20)throw Error('День должен быть от 1 до 21');week=Math.floor(index/7);day=index%7;state.last=index;tab='learn';save();render();}
function render(){const i=week*7+day,l=course[i];$('#weeks').innerHTML=weeks.map((w,n)=>`<button class="${n===week?'active':''}" data-week="${n}"><span>НЕДЕЛЯ ${n+1} / ${w.label}</span><b>${w.title}</b></button>`).join('');$('#weeks').querySelectorAll('button').forEach(b=>b.onclick=()=>selectDay(Number(b.dataset.week)*7));const count=Array.from({length:7},(_,n)=>week*7+n).filter(completed).length;$('#weekHeader').innerHTML=`<div class="weekHeading"><div><span class="eyebrow">НЕДЕЛЯ ${week+1}</span><h2>${weeks[week].title}</h2><p class="muted">${weeks[week].goal}</p></div><span class="chip">${count} / 7 пройдено</span></div>`;$('#days').innerHTML=Array.from({length:7},(_,n)=>`<button data-day="${n}" class="${n===day?'active':''} ${completed(week*7+n)?'complete':''}" aria-current="${n===day?'step':'false'}">День ${n+1}</button>`).join('');$('#days').querySelectorAll('button').forEach(b=>b.onclick=()=>selectDay(week*7+Number(b.dataset.day)));$('#lesson').innerHTML=`<div class="lessonTitle"><span class="eyebrow">МИССИЯ ${String(i+1).padStart(2,'0')} / 21</span><h2>${esc(l.title)}</h2><p>${esc(l.goal)}</p><div class="statusrow"><span class="${state.solved.includes(i+'-code')?'solved':''}">Код ${state.solved.includes(i+'-code')?'✓':'○'}</span><span class="${state.solved.includes(i+'-quiz')?'solved':''}">Проверка понимания ${state.solved.includes(i+'-quiz')?'✓':'○'}</span><span class="${state.practice.includes(i)?'solved':''}">Проект ${state.practice.includes(i)?'✓':'○'}</span></div></div><div class="tabs" role="tablist">${[['learn','01 · Разобраться'],['code','02 · Написать код'],['quiz','03 · Проверить себя'],['project','04 · Собрать проект']].map(([v,t])=>`<button role="tab" aria-selected="${tab===v}" class="${tab===v?'active':''}" data-tab="${v}">${t}</button>`).join('')}</div><div id="content" role="tabpanel"></div>`;$('#lesson').querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render();});renderContent();updateProfile();}
function setTab(v){tab=v;render();}
function feedback(id,msg,kind=''){const node=$(id);node.innerHTML=`<div class="feedback ${kind}" role="status">${msg}</div>`;}
// Это проверка ответа учебного задания, не компилятор произвольного кода.
function canonical(code){const parts=String(code).trim().match(/"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'|\S/g)||[];return parts.join('').replace(/;+$/,'');}
function matchesCode(value,answers){return answers.some(a=>canonical(a)===canonical(value)||(/^[\p{L}\p{N}_@-]+$/u.test(a)&&a.toUpperCase()===value.trim().toUpperCase()));}
function award(kind){const id=state.last+'-'+kind;if(!state.solved.includes(id)){state.solved.push(id);save();renderStatus();}}
function renderStatus(){if(typeof addAndroidBridge==='function')addAndroidBridge();const i=state.last;const row=$('.statusrow');if(row)row.innerHTML=`<span class="${state.solved.includes(i+'-code')?'solved':''}">Код ${state.solved.includes(i+'-code')?'✓':'○'}</span><span class="${state.solved.includes(i+'-quiz')?'solved':''}">Проверка понимания ${state.solved.includes(i+'-quiz')?'✓':'○'}</span><span class="${state.practice.includes(i)?'solved':''}">Проект ${state.practice.includes(i)?'✓':'○'}</span>`;}
function renderTheory(l) {
    const d = l.deepDive;
    if (!d) return l.theory.map(p => `<p>${esc(p)}</p>`).join('');
    return `<p class="note">Не спеши к заданию. Сначала прочитай объяснение, предскажи результат примера, затем сверься с разбором. Если термин непонятен, вернись к соответствующему разделу.</p>
    <nav class="theoryContents" aria-label="Разделы урока"><b>В этом уроке</b>${d.sections.map((s,n)=>`<a href="#theory-${n}">${n+1}. ${esc(s.title)}</a>`).join('')}<a href="#theory-mistakes">Типичные ошибки</a><a href="#theory-check">Проверка перед практикой</a></nav>
    ${d.sections.map((s,n)=>`<section class="theorySection" id="theory-${n}"><span class="tag">ШАГ ${n+1}</span><h4>${esc(s.title)}</h4>${s.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')}${s.code?`<pre><code>${esc(s.code)}</code></pre><p class="exampleExplanation"><b>Разбор:</b> ${esc(s.explanation)}</p>`:''}</section>`).join('')}
    <section class="theorySection" id="theory-mistakes"><h4>Типичные ошибки</h4><ul>${d.pitfalls.map(p=>`<li>${esc(p)}</li>`).join('')}</ul></section>
    <section class="theorySection" id="theory-check"><h4>Проверь понимание перед кодом</h4><p>${esc(d.question)}</p><details><summary>Свериться с объяснением</summary><p>${esc(d.answer)}</p></details><p class="muted">Попробуй ответить своими словами. Если пока не получается — перечитай нужный раздел и разложи пример на шаги.</p></section>
    <details class="theoryCheatsheet"><summary>Краткая шпаргалка</summary>${l.theory.map(p=>`<p>${esc(p)}</p>`).join('')}</details><h4>Собираем пример урока</h4>`;
}

function renderContent(){const i=state.last,l=course[i],c=$('#content');if(tab==='learn'){c.innerHTML=`<article class="card"><span class="tag">ТЕОРИЯ / 30–45 МИНУТ</span><h3>Разбор темы по шагам</h3>${renderTheory(l)}<div class="codeHeader"><span>Пример · ${weeks[week].title}</span><button id="copy" class="small">Копировать</button></div><pre><code>${esc(l.code)}</code></pre><p class="note">Фрагменты Android и Spring выполняются внутри проекта с зависимостями и импортами. Самостоятельный Kotlin запускай в Playground. Учебный пример — отправная точка, дальше код пишешь ты.</p><a href="${l.source}" target="_blank" rel="noopener">Официальный материал по теме</a><div class="actions"><button id="goCode" class="primary">Начать задание</button></div></article>`;$('#copy').onclick=()=>copy(l.code,$('#copy'));$('#goCode').onclick=()=>setTab('code');}
if(tab==='code'){c.innerHTML=`<article class="card"><span class="tag">КОД-КВЕСТ / +50 XP</span><h3>Напиши решение</h3><p>${esc(l.task)}</p><label for="answer" class="muted">Твой код или короткий ответ</label><textarea id="answer" spellcheck="false" autocapitalize="off" placeholder="Напиши здесь самостоятельно…">${esc(state.drafts[i]||'')}</textarea><div class="actions"><button id="checkCode" class="primary">Проверить</button><button id="hint">Подсказка</button></div><div id="codeFeedback" aria-live="polite"></div><details><summary>Разбор и принятые варианты</summary><p>${esc(l.why)}</p>${l.answers.map(a=>`<pre><code>${esc(a)}</code></pre>`).join('')}<p class="muted">Сначала попробуй сам. Просмотр решения не начисляет очки.</p></details><p class="note">Проверка сравнивает ответ с учебными вариантами; это не запуск кода. Иное корректное решение может не распознаться. Полноценную программу проверь в IDE${week===0?' или Kotlin Playground':''}.</p><div class="actions">${week===0?'<a target="_blank" rel="noopener" href="https://play.kotlinlang.org/">Открыть Kotlin Playground</a>':''}<button id="goQuiz">Проверить понимание</button></div></article>`;$('#answer').oninput=e=>{state.drafts[i]=e.target.value;save();};$('#hint').onclick=()=>feedback('#codeFeedback',esc(l.hint));$('#checkCode').onclick=()=>{const v=$('#answer').value;if(!v.trim())return feedback('#codeFeedback','Напиши ответ — можно начать с подсказки.','error');if(matchesCode(v,l.answers)){state.codeSnapshots=state.codeSnapshots||{};state.codeSnapshots[i]=v;save();award('code');if(typeof addAndroidBridge==='function')addAndroidBridge();feedback('#codeFeedback','Верно! +50 XP за первое решение. '+esc(l.why),'success');}else feedback('#codeFeedback','Этот вариант не совпал с учебным решением. '+esc(l.hint)+' Проверь имена, типы, скобки и формулировку задания.','error');};$('#goQuiz').onclick=()=>setTab('quiz');}
if(tab==='quiz'){const selected=Array.isArray(state.checks[i])?state.checks[i]:[];c.innerHTML=`<article class="card"><span class="tag">ПРОВЕРКА ПОНИМАНИЯ / +50 XP</span><h3>${esc(l.quiz)}</h3><p class="muted">Выбери все правильные варианты. Их может быть несколько.</p><div class="options">${l.options.map((o,n)=>`<label class="option"><input type="checkbox" value="${n}" ${selected.includes(n)?'checked':''}><span>${esc(o)}</span></label>`).join('')}</div><div class="actions"><button id="checkQuiz" class="primary">Проверить выбор</button><button id="quizHint">Направляющая подсказка</button></div><div id="quizFeedback" aria-live="polite"></div><details><summary>Показать верные варианты и объяснение</summary><ul>${l.correct.map(n=>`<li>${esc(l.options[n])}</li>`).join('')}</ul><p>${l.theory.map(esc).join(' ')}</p></details><div class="actions"><button id="goProject">К практике проекта</button></div></article>`;c.querySelectorAll('input').forEach(x=>x.onchange=()=>{state.checks[i]=Array.from(c.querySelectorAll('input:checked')).map(n=>Number(n.value));save();});$('#checkQuiz').onclick=()=>{const got=Array.from(c.querySelectorAll('input:checked')).map(n=>Number(n.value));if(!got.length)return feedback('#quizFeedback','Выбери хотя бы один вариант.','error');const ok=got.length===l.correct.length&&got.every(n=>l.correct.includes(n));if(ok){award('quiz');feedback('#quizFeedback','Верно! Ты выбрал все правильные варианты. +50 XP за первое решение. Теперь примени это в проекте.','success');}else{const wrong=got.filter(n=>!l.correct.includes(n)).map(n=>l.options[n]);feedback('#quizFeedback',wrong.length?'Пересмотри: '+wrong.map(esc).join('; ')+'. Сверь эти утверждения с разбором урока.':'Выбранные варианты верны, но есть ещё правильные. Вспомни все части урока.','error');}};$('#quizHint').onclick=()=>feedback('#quizFeedback','Обоснуй каждый выбранный вариант примером из кода. '+esc(l.theory[0]));$('#goProject').onclick=()=>setTab('project');}
if(tab==='project'){const ready=state.solved.includes(i+'-code')&&state.solved.includes(i+'-quiz');c.innerHTML=`<article class="card"><span class="tag">ПРАКТИКА / +100 XP / 60–100 МИНУТ</span><h3>Твой шаг к Habit Tracker</h3><p>${esc(l.practice)}</p><div class="note">Напиши код в Android Studio или IntelliJ IDEA, запусти и проверь. Этот этап ты подтверждаешь сам: сайт не видит твой проект и не проверяет его выполнение.</div><div class="options"><label class="option"><input id="ran" type="checkbox" ${state.practice.includes(i)?'checked':''}>Код запускается, я проверил обычный сценарий</label><label class="option"><input id="edge" type="checkbox" ${state.practice.includes(i)?'checked':''}>Проверены ошибки и крайние случаи задания</label><label class="option"><input id="explain" type="checkbox" ${state.practice.includes(i)?'checked':''}>Я могу объяснить решение и повторить основную часть без образца</label></div><div class="actions"><button id="finishDay" class="primary">${state.practice.includes(i)?'Практика подтверждена ✓':'Подтвердить свою практику'}</button><button id="nextDay">${i===20?'К сертификату':'Следующая миссия'}</button></div><div id="projectFeedback" aria-live="polite"></div>${!ready?'<p class="muted">Для очков за практику сначала реши код-квест и проверку понимания.</p>':''}</article><article class="card"><h3>Как закрепить уверенность</h3><p>Закрой образец. Повтори главную функцию или экран по памяти. Затем измени требование — добавь поле, фильтр или обработку ошибки. Если застрял, возьми одну подсказку и продолжи.</p><p class="muted">Все дни доступны: можно вернуться к сложной теме. Переход к следующему дню сам по себе не засчитывает задания.</p></article>`;$('#finishDay').onclick=()=>{if(!ready)return feedback('#projectFeedback','Сначала реши код-квест и проверку понимания.','error');if(!['#ran','#edge','#explain'].every(s=>$(s).checked))return feedback('#projectFeedback','Запусти проект, проверь граничные случаи и объясни решение. Отметь выполненные пункты.','error');if(!state.practice.includes(i)){state.practice.push(i);save();}renderStatus();$('#days').querySelector(`[data-day="${day}"]`).classList.add('complete');feedback('#projectFeedback','Миссия пройдена! Практика подтверждена тобой. +100 XP за первое прохождение.','success');};$('#nextDay').onclick=()=>i===20?showCertificate():selectDay(i+1);}}
async function copy(text,button){try{await navigator.clipboard.writeText(text);button.textContent='Скопировано';}catch(e){button.textContent='Выдели код и скопируй';}}
function openModal(html){$('#modalBody').innerHTML=html;$('#modal').showModal();}
function showCertificate(){const count=Array.from({length:21},(_,i)=>i).filter(completed).length;if(count<21){openModal(`<h2>Твой финальный трофей</h2><p>Заверши все 21 миссию: код, проверку понимания и самостоятельную практику.</p><div class="bar"><span style="width:${count/21*100}%"></span></div><p>${count} из 21 дней завершено · ${score()} XP</p><p class="muted">Это игровой сертификат учебного центра. Он не является аккредитованным документом и не подтверждает проверку проекта преподавателем.</p>`);return;}openModal(`<div id="certControls"><h3>Как подписать сертификат?</h3><label for="certName">Имя</label><input id="certName" type="text" maxlength="80" value="${esc(state.name)}" placeholder="Твоё имя"><div class="actions"><button id="makeCert" class="primary">Создать сертификат</button></div><p class="muted">После создания можно сохранить как PDF через печать браузера.</p></div>`);$('#makeCert').onclick=()=>{state.name=$('#certName').value.trim();if(!state.name){$('#certName').focus();return;}save();const date=new Date().toLocaleDateString('ru-RU');$('#modalBody').innerHTML=`<div class="cert"><span class="eyebrow">HABIT LAB / CERTIFICATE</span><h2>Маршрут завершён</h2><div class="seal">✦</div><p>Игровой сертификат участника</p><strong>${esc(state.name)}</strong><p>прошёл 21 учебную миссию по маршруту</p><h3>Kotlin & Android · Java · Spring Boot</h3><p>42 проверяемых задания · 21 самостоятельно подтверждённая практика</p><p>${score()} XP · ${date}</p><p class="muted">Не является документом об образовании.<br>Практический проект подтверждён участником, без внешней проверки.</p></div><div id="certControls" class="actions"><button id="printCert" class="primary">Печать / сохранить PDF</button></div>`;$('#printCert').onclick=()=>window.print();};}
$('#certificate').onclick=showCertificate;$('.close').onclick=()=>$('#modal').close();$('#modal').onclick=e=>{if(e.target===$('#modal'))$('#modal').close();};
$('#resources').onclick=()=>openModal(`<h2>Один продукт, три части</h2><div class="projectFlow"><div><b>Kotlin / Android</b><br>XML: TextView + RecyclerView · Compose: список, форма и состояние · ViewModel · Repository · Retrofit · корутины</div><div><b>Spring Boot / Java</b><br>REST Controller и Admin Controller используют общий HabitService → JpaRepository → H2</div><div><b>Админка / Java + Thymeleaf</b><br>Защищённые страницы: список, создание, редактирование, удаление. Android видит изменения после обновления данных.</div></div><h3>Маршрут и материалы</h3><ul><li><a target="_blank" rel="noopener" href="https://kotlinlang.org/docs/kotlin-tour-welcome.html">Kotlin Tour</a> — основы в браузере.</li><li><a target="_blank" rel="noopener" href="https://kotlinlang.org/docs/koans.html">Kotlin Koans</a> — дополнительная практика синтаксиса; особенно полезна после Java.</li><li><a target="_blank" rel="noopener" href="https://developer.android.com/courses/android-basics-compose/course">Android Basics with Compose</a> — официальный Android-курс.</li><li><a target="_blank" rel="noopener" href="https://developer.android.com/develop/ui/views/layout/recyclerview">RecyclerView</a> — официальное руководство по Views.</li><li><a target="_blank" rel="noopener" href="https://dev.java/learn/">Dev.java</a> — Java, классы, коллекции и инструменты.</li><li><a target="_blank" rel="noopener" href="https://spring.io/guides/gs/rest-service/">Spring: REST</a> и <a target="_blank" rel="noopener" href="https://spring.io/guides/gs/accessing-data-jpa/">Spring: JPA</a> — сервер и база.</li><li><a target="_blank" rel="noopener" href="https://spring.io/guides/gs/securing-web/">Spring Security</a> — защита админки.</li></ul><h3>Подготовка среды</h3><p>Android Studio с Android SDK и эмулятором; IntelliJ IDEA и JDK 21 для Java; Spring Initializr с совместимой стабильной версией Spring Boot. Для Kotlin-основ установка не нужна: используй Playground.</p><p>Каждый день: 30–45 минут теории, 20–30 минут заданий, 60–100 минут собственного кода и 10 минут повторения. Если тема не закрепилась, повтори день — календарь не важнее понимания.</p><p class="note">Курс ведёт к учебному полному CRUD-приложению. Работа с production, сложная авторизация, offline-синхронизация и публикация в магазине требуют дальнейшего обучения.</p>`);
$('#export').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='habit-lab-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('#import').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>1000000)throw Error('Файл слишком большой');state=validateState(JSON.parse(await f.text()));week=Math.floor(state.last/7);day=state.last%7;save();render();$('#storageMessage').textContent='Прогресс импортирован';}catch(err){$('#storageMessage').textContent='Не удалось импортировать: нужен файл экспорта Habit Lab.';}e.target.value='';};
async function init(){try{const r=await fetch('course.json');if(!r.ok)throw Error('HTTP '+r.status);course=await r.json();if(course.length!==21)throw Error('Неполный курс');week=Math.floor(state.last/7);day=state.last%7;render();save();if(document.modelContext?.registerTool){try{await document.modelContext.registerTool({name:'habitlab_read_progress',description:'Read completed learning missions and current day.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({xp:score(),completedDays:Array.from({length:21},(_,i)=>i).filter(completed).map(i=>i+1),currentDay:state.last+1})});await document.modelContext.registerTool({name:'habitlab_open_day',description:'Navigate to a learning day without marking it completed.',inputSchema:{type:'object',properties:{day:{type:'integer',minimum:1,maximum:21}},required:['day'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||!Number.isInteger(input.day)||input.day<1||input.day>21)throw Error('Invalid day');selectDay(input.day-1);return {currentDay:state.last+1,title:course[state.last].title};}});}catch(e){console.warn('WebMCP недоступен');}}}catch(e){$('#lesson').innerHTML='<div class="card"><h2>Не удалось загрузить уроки</h2><p>Обнови страницу, чтобы попробовать снова. Твой сохранённый прогресс останется.</p><button onclick="location.reload()">Повторить</button></div>';}}

